/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { DuxliButtonVariant } from "./components/duxli-button/duxli-button";
export namespace Components {
    interface DuxliButton {
        /**
          * Variant for the button.
          * @default 'outlined'
         */
        "variant": DuxliButtonVariant;
    }
}
declare global {
    interface HTMLDuxliButtonElement extends Components.DuxliButton, HTMLStencilElement {
    }
    var HTMLDuxliButtonElement: {
        prototype: HTMLDuxliButtonElement;
        new (): HTMLDuxliButtonElement;
    };
    interface HTMLElementTagNameMap {
        "duxli-button": HTMLDuxliButtonElement;
    }
}
declare namespace LocalJSX {
    interface DuxliButton {
        /**
          * Variant for the button.
          * @default 'outlined'
         */
        "variant"?: DuxliButtonVariant;
    }
    interface IntrinsicElements {
        "duxli-button": DuxliButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "duxli-button": LocalJSX.DuxliButton & JSXBase.HTMLAttributes<HTMLDuxliButtonElement>;
        }
    }
}
