/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DuxliButton {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDuxliButtonElement extends Components.DuxliButton, HTMLStencilElement {
    }
    var HTMLDuxliButtonElement: {
        prototype: HTMLDuxliButtonElement;
        new (): HTMLDuxliButtonElement;
    };
    interface HTMLElementTagNameMap {
        "duxli-button": HTMLDuxliButtonElement;
    }
}
declare namespace LocalJSX {
    interface DuxliButton {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "duxli-button": DuxliButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "duxli-button": LocalJSX.DuxliButton & JSXBase.HTMLAttributes<HTMLDuxliButtonElement>;
        }
    }
}
